apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-nonprod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kerolosashraf2025/cloud-native-devops-nti
    targetRevision: main
    path: gitops/nonprod/sample-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
