apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: mongo-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: /nonprod/sample-app/mongodb-uri
