apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://kerolosashraf2025_db_user:hs67oAkpNoJA1qr5@nti-nonprod-mongo.85tyg4y.mongodb.net/?appName=nti-nonprod-mongo
